// <auto-generated />
using System;
using FOOTBALMAPSV2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FOOTBALMAPSV2.Migrations
{
    [DbContext(typeof(FootballMapsDbContext))]
    [Migration("20260403165826_AddTeamDetails")]
    partial class AddTeamDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FOOTBALMAPSV2.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocalFood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaturalResources")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupportCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 34,
                            CountryId = 1,
                            Culture = "Kozmopolit yapı, müzeler",
                            History = "Tarihi Yarımada, Bizans ve Osmanlı başkenti.",
                            Latitude = 41.008200000000002,
                            LocalFood = "Balık Ekmek, Kumpir, Sultanahmet Köftesi",
                            Longitude = 28.978400000000001,
                            Name = "İstanbul",
                            NaturalResources = "Boğaz, ormanlar",
                            SupportCount = 0
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Culture = "Anıtkabir, Devlet Opera ve Balesi",
                            History = "Cumhuriyetin başkenti, Frigya dönemi.",
                            Latitude = 39.933399999999999,
                            LocalFood = "Ankara Döneri, Ankara Simidi, Beypazarı Kurusu",
                            Longitude = 32.859699999999997,
                            Name = "Ankara",
                            NaturalResources = "Tuz Gölü havzası, ormanlar",
                            SupportCount = 0
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 1,
                            Culture = "Saat Kulesi, Boyoz kültürü",
                            History = "Efes Antik Kenti, İyonya uygarlığı.",
                            Latitude = 38.419199999999996,
                            LocalFood = "Boyoz, Kumru, Bomba, Gevrek",
                            Longitude = 27.128699999999998,
                            Name = "İzmir",
                            NaturalResources = "Ege Denizi, incir, zeytin ağaçları",
                            SupportCount = 0
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 1,
                            Culture = "Ulu Cami, Koza Han",
                            History = "Osmanlı Devleti'nin ilk başkenti.",
                            Latitude = 40.188499999999998,
                            LocalFood = "İskender Kebap, Kestane Şekeri",
                            Longitude = 29.061,
                            Name = "Bursa",
                            NaturalResources = "Uludağ, kaplıcalar",
                            SupportCount = 0
                        },
                        new
                        {
                            Id = 61,
                            CountryId = 1,
                            Culture = "Karadeniz kültürü, horon",
                            History = "Trabzon İmparatorluğu, Sümela Manastırı.",
                            Latitude = 41.002699999999997,
                            LocalFood = "Akçaabat Köftesi, Kuymak, Hamsi",
                            Longitude = 39.716799999999999,
                            Name = "Trabzon",
                            NaturalResources = "Uzungöl, ormanlık alanlar",
                            SupportCount = 0
                        },
                        new
                        {
                            Id = 55,
                            CountryId = 1,
                            Culture = "Gazi Müzesi, Bandırma Vapuru",
                            History = "Milli Mücadele'nin başladığı şehir.",
                            Latitude = 41.286700000000003,
                            LocalFood = "Samsun Pidesi, Bafra Pidesi",
                            Longitude = 36.329999999999998,
                            Name = "Samsun",
                            NaturalResources = "Kızılırmak ve Yeşilırmak deltaları",
                            SupportCount = 0
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 1,
                            Culture = "Medeniyetler Korosu, Mozaik Müzesi",
                            History = "Antik çağlardan günümüze medeniyetlerin kesişme noktası.",
                            Latitude = 36.206600000000002,
                            LocalFood = "Künefe, Oruk, Tepsi Kebabı",
                            Longitude = 36.157200000000003,
                            Name = "Hatay",
                            NaturalResources = "Asi Nehri, Titus Tüneli",
                            SupportCount = 0
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 1,
                            Culture = "Çifte Minareli Medrese, Yakutiye Medresesi",
                            History = "Anadolu'nun en eski yerleşim merkezlerinden biri.",
                            Latitude = 39.904299999999999,
                            LocalFood = "Cağ Kebabı, Kadayıf Dolması",
                            Longitude = 41.267899999999997,
                            Name = "Erzurum",
                            NaturalResources = "Palandöken Dağı, Tortum Şelalesi",
                            SupportCount = 0
                        });
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Türkiye"
                        });
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Trendyol Süper Lig",
                            Tier = "1. Kademe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Trendyol 1. Lig",
                            Tier = "2. Kademe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TFF 2. Lig",
                            Tier = "3. Kademe"
                        });
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achievements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("FoundationYear")
                        .HasColumnType("int");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 34,
                            FoundationYear = 1905,
                            LeagueId = 1,
                            LogoUrl = "/images/teams/Galatasaray_Sports_Club_Logo.svg.png",
                            Name = "Galatasaray"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 34,
                            FoundationYear = 1907,
                            LeagueId = 1,
                            LogoUrl = "/images/teams/Fenerbahçe_SK.png",
                            Name = "Fenerbahçe"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 34,
                            FoundationYear = 1903,
                            LeagueId = 1,
                            LogoUrl = "/images/teams/BesiktasJK-Logo.svg.png",
                            Name = "Beşiktaş"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 6,
                            FoundationYear = 1910,
                            LeagueId = 2,
                            LogoUrl = "/images/teams/MKE_Ankaragücü_logo.png",
                            Name = "MKE Ankaragücü"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 6,
                            FoundationYear = 1923,
                            LeagueId = 2,
                            LogoUrl = "/images/teams/Genclerbirligi.png",
                            Name = "Gençlerbirliği"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 35,
                            FoundationYear = 1925,
                            LeagueId = 1,
                            LogoUrl = "/images/teams/Göztepe.png",
                            Name = "Göztepe"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 16,
                            FoundationYear = 1963,
                            LeagueId = 3,
                            LogoUrl = "/images/teams/330px-Bursaspor-amblem.png",
                            Name = "Bursaspor"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 61,
                            FoundationYear = 1967,
                            LeagueId = 1,
                            LogoUrl = "/images/teams/TrabzonsporAmblemi.png",
                            Name = "Trabzonspor"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 55,
                            FoundationYear = 1965,
                            LeagueId = 1,
                            LogoUrl = "/images/teams/Samsunspor_logo.png",
                            Name = "Samsunspor"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 31,
                            FoundationYear = 1967,
                            LeagueId = 1,
                            LogoUrl = "/images/teams/Hatayspor.png",
                            Name = "Hatayspor"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 25,
                            FoundationYear = 2005,
                            LeagueId = 2,
                            LogoUrl = "/images/teams/Erzurumsporfk.png",
                            Name = "Erzurumspor FK"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.City", b =>
                {
                    b.HasOne("FOOTBALMAPSV2.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.Team", b =>
                {
                    b.HasOne("FOOTBALMAPSV2.Models.City", "City")
                        .WithMany("Teams")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FOOTBALMAPSV2.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId");

                    b.Navigation("City");

                    b.Navigation("League");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.City", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.League", b =>
                {
                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
