// <auto-generated />
using FOOTBALMAPSV2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FOOTBALMAPSV2.Migrations
{
    [DbContext(typeof(FootballMapsDbContext))]
    [Migration("20260317225227_UpdateTeamLogos")]
    partial class UpdateTeamLogos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FOOTBALMAPSV2.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalFood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaturalResources")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupportCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 34,
                            CountryId = 1,
                            Culture = "Kozmopolit yapı, müzeler",
                            History = "Tarihi Yarımada, Bizans ve Osmanlı başkenti.",
                            LocalFood = "Balık Ekmek, Kumpir, Sultanahmet Köftesi",
                            Name = "İstanbul",
                            NaturalResources = "Boğaz, ormanlar",
                            SupportCount = 0
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Culture = "Anıtkabir, Devlet Opera ve Balesi",
                            History = "Cumhuriyetin başkenti, Frigya dönemi.",
                            LocalFood = "Ankara Döneri, Ankara Simidi, Beypazarı Kurusu",
                            Name = "Ankara",
                            NaturalResources = "Tuz Gölü havzası, ormanlar",
                            SupportCount = 0
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 1,
                            Culture = "Saat Kulesi, Boyoz kültürü",
                            History = "Efes Antik Kenti, İyonya uygarlığı.",
                            LocalFood = "Boyoz, Kumru, Bomba, Gevrek",
                            Name = "İzmir",
                            NaturalResources = "Ege Denizi, incir, zeytin ağaçları",
                            SupportCount = 0
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 1,
                            Culture = "Ulu Cami, Koza Han",
                            History = "Osmanlı Devleti'nin ilk başkenti.",
                            LocalFood = "İskender Kebap, Kestane Şekeri",
                            Name = "Bursa",
                            NaturalResources = "Uludağ, kaplıcalar",
                            SupportCount = 0
                        },
                        new
                        {
                            Id = 61,
                            CountryId = 1,
                            Culture = "Karadeniz kültürü, horon",
                            History = "Trabzon İmparatorluğu, Sümela Manastırı.",
                            LocalFood = "Akçaabat Köftesi, Kuymak, Hamsi",
                            Name = "Trabzon",
                            NaturalResources = "Uzungöl, ormanlık alanlar",
                            SupportCount = 0
                        });
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Türkiye"
                        });
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("FoundationYear")
                        .HasColumnType("int");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 34,
                            FoundationYear = 1905,
                            LogoUrl = "/images/teams/Galatasaray_Sports_Club_Logo.svg.png",
                            Name = "Galatasaray"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 34,
                            FoundationYear = 1907,
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/tr/8/86/Fenerbah%C3%A7e_SK.png",
                            Name = "Fenerbahçe"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 34,
                            FoundationYear = 1903,
                            LogoUrl = "/images/teams/BesiktasJK-Logo.svg.png",
                            Name = "Beşiktaş"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 6,
                            FoundationYear = 1910,
                            LogoUrl = "/images/teams/MKE_Ankaragücü_logo.png",
                            Name = "MKE Ankaragücü"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 6,
                            FoundationYear = 1923,
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/tr/1/15/Gen%C3%A7lerbirli%C4%9Fi.png",
                            Name = "Gençlerbirliği"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 35,
                            FoundationYear = 1925,
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/tr/b/bf/G%C3%B6ztepe_Armas%C4%B1.png",
                            Name = "Göztepe"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 16,
                            FoundationYear = 1963,
                            LogoUrl = "/images/teams/330px-Bursaspor-amblem.png",
                            Name = "Bursaspor"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 61,
                            FoundationYear = 1967,
                            LogoUrl = "/images/teams/TrabzonsporAmblemi.png",
                            Name = "Trabzonspor"
                        });
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.City", b =>
                {
                    b.HasOne("FOOTBALMAPSV2.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.Team", b =>
                {
                    b.HasOne("FOOTBALMAPSV2.Models.City", "City")
                        .WithMany("Teams")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.City", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FOOTBALMAPSV2.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
